### PR TITLE
Back to Custom Statuses

### PR DESCRIPTION
**Pull request by imath**
Hi everyone,

First I apologise I haven't found the time earlier to work on this project. In early August, I've tried to carry on the work @tomjn started with the taxonomy direction. But I wasn't able to make it work on the front-end. Moreover I had this feeling It was introducing some complexity (especially for me 😊 ) to achieve something statuses are doing more simply. So I went back in the history of the plugin and started to explore a bit more the Custom Statuses direction.

_This PR contains all the changes I will use for the WordCamp Paris 2018 call for speakers. It will be interesting for us to have a real testing period about most of the features. BTW this PR comes from a fork i've made on the @WordCampParis Github repository._

I chose to use **Custom Private Statuses**, as it was the easiest way to make sure only Reviewers could review privately and speakers could only see their own Talk Proposals. And it solves a lot of issues with the Admin UI (as WordPress is generating views about each of these statuses).

Once done, i've tried to fix many of the remaining [issues](https://github.com/imath/wordcamp-talks/issues) : 
- #40, #41, #32, #23, #22, #18 should be fixed.
- I've worked a lot on #36 but there are probably some other possible improvements.

This time i've worked with VVV & the [WordPress Meta Environment](https://github.com/WordPress/meta-environment). I've added unit tests, removed a lot of custom hooks, wrappers and reorganised folders, files and some functions. You can check the commits to have a detailed review of this PR.

## The Admin UI

I'm removing the regular submit box to use a specific one.

Talk Proposals Statuses

We've been talking about it with @iandunn : it's allowing us to integrate the Plugin with the existing WordCamp Post Types. In particular the Session and Speaker ones. When a Talk Proposal is selected and the Speaker Post type (i'll come back to the speaker post type a bit later), then a button is allowing to init a Session in draft mode with the Talk Proposal data.

Talk Proposals Statuses

Once the Session is inited, this button is becoming a link to edit the Session.

## The Front-End

I've also built an integration with the WordCamp Speaker's post type base on the User's description. The goal is to provide a default description based on the one existing on the WordPress.org profile of the user and allow him to use it for the WordCamp or to customise it for this specific WordCamp without having an impact on the one he has on Profiles.WordPress.org. In short, when editing the biographical information, the user is in fact editing a Speaker Post Type.

Front-end Profile

So this gives a real utility to the front end profile included into the plugin. I also think @tomjn 's idea to add some information about the status of the talk on the front-end is a really great idea (See #18). So i've added prefixes to title.

Prefixes

I'd like to have your opinions about these suggestions before doing anything with it as it's removing a lot a work we've accomplished so far.

### CODE REVIEW

**Comment by iandunn** [comment]
The sheer amount of changes here makes it very difficult to review, but I'm happy to trust your judgement with regards to custom statuses.

I am concerned about bringing in extraneous features, though, like Slack notifications. My understanding was that we'd decided that v1 would be a lean version tailored to WordCamp.org's needs, and were working to remove a lot of the features that were non-essential, and the code patterns that were overkill for WordCamp.org (e.g., #36).

**Comment by tomjn** [comment]
My personal thoughts are that the statuses taxonomy etc are all a result of the frontend UI, and that a better solution would be a REST powered React application, allowing the same UI on the front and backends, and sidestepping entirely the problem statuses works around.

I intended to implement this but I've been busy wrangling my own WordCamp happening this weekend

**Comment by imath** [comment]
@iandunn i agree it’s a huge PR, i’m going to close it. As i needed something for WordCamp Paris i took a lot of decisions by myself so it’s probably best the fork on the WordCampParis account lives his short life apart :) 

It’s ready & matches our specific needs for this year’s event: slack notifications & export feature to satisfy the WP importer format.

@tomjn feel free to improve the plugin with React and the rest API, it’s very promising.

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
Only matches WordCamp Paris needs. Something more generic would be better.

**Pull request closed without merging**
