### PR TITLE
:sparkles: Add wpgod for tracking wordcamp-talks

### PR DESCRIPTION
**Pull request by Gmulti**
I suggest you add WP GoD to track potential plugin errors.
If anyone wants access to the dashboard, contact me by email or on the online support of the site. (Slack FR also)

### CODE REVIEW

**Comment by imath** [comment]
Hi @Gmulti 

Thanks for your PR, i'm pretty amazed by the number of files: 36 !! If i remember well when we talked together for other projects, WP God tracks errors and we can get data/stats about it.

The 36 files are to be shipped within the plugin?

If so, i'd like to have other team members opinion about it. Personally i don't mind putting it on the development site i'm using but having it on any website is another story :)

Putting the link to your website so that team members can have an idea about what WP God can bring to the project: https://wp-god.com/en/

**Comment by Gmulti** [comment]
Hi ! 
WP GoD is a library so effectively, all files are required. It is self-managed and does not run if there are not the prerequisites (PHP version, curl, ...)

**Comment by grappler** [comment]
I don't think it the library is needed to track errors. Reporting issues in support works fine. This will cause an extra barrier on getting the code on WordCamp.org.

There is always a problem of privacy when data is being sent to a third party.

**Comment by Gmulti** [comment]
So, you don't want to get ahead of potential errors ?
And what is the barrier to retrieve the code ?

Using github, you already use a third party ... :)

**Comment by grappler** [comment]
> So, you don't want to get ahead of potential errors ?

As I understand it the plugin is being built to be used on WordCamp.org. It is not planned to used on random sites. I would prefer to use travis to test the code in different environments before the code is deployed on a production site.

 > So, you don't want to get ahead of potential errors ?

The extra barrier is there is extra code to review and the people from the WordPress foundation need to be on board with this.

> Using github, you already use a third party

Yes, the code is public but there is a question of what data is sent to your servers and who has access to it as this is an open source project.

This is just my opinion and I am not a person who makes the final decision.

**Comment by Gmulti** [comment]
The tests are good but they should not exclude any tracking system (I speak in general)
You can see what data is sent to the server :) (this is in the library)

**Comment by imath** [comment]
Hi @grappler & @Gmulti 

First many thanks to you both for your contributions to this.

@grappler 's concern was also in my mind about WP God. 

On the other hand, i see @Gmulti 's PR as a way to contribute to the project so i'd like, if it's possible, to avoid any frustration for anyone.

This is my suggestion:

Test it on my test drive **only** and see what WP God can bring us.

Correct me if i'm wrong: from what i understand, the service is listening to any errors. Using phpunit is only preventing errors we are already aware of.

For a more wide use, @grappler is absolutely right: this needs to be validated by the WordCamp.org team. I think @andreamiddleton and @jennybeaumont opinions are very important in this case.

**Comment by andreamiddleton** [comment]
I'd actually tag Ian Dunn on this issue. :) The wordcamp.org network has some specific code requirements related to security that he can speak to better than I can.

**Comment by jennybeaumont** [comment]
I'm gonna agree with @grappler that we do not need such a third party service to ensure the quality of our code, especially one that requires including additional files to the plugin itself. And I must say, although I have the utmost respect for @Gmulti and his project, I find this a tad spammy 😞

**Comment by Gmulti** [comment]
Really sorry it was spam. I should have suggested PR with sentry.io
I close the PR. It's too complex.

**Comment by iandunn** [comment]
Sorry for the late response. I agree that there could be some value in some form of monitoring, but that would definitely need to be a separate proposal. I don't see any reason it should be tied to this specific project.

Sending user/server/etc data to a 3rd party would definitely be a non-starter, so any proposal would need to be for a tool that stores the data locally.

**Pull request closed without merging**
