### PR TITLE
Post statuses

### PR DESCRIPTION
**Pull request by tomjn**
The aim of this PR is to add several custom post statuses as a replacement for the workflow post meta and metabox

screen shot 2017-01-11 at 15 35 43
screen shot 2017-01-11 at 15 36 02

Todo:

- [x] Remove the Workflow metabox
- [x] Add the custom post statuses
- [x] Set their visibility
- [x] Adjust the talks queries to show all post statuses except draft
- [x] Adjust the talks queries to only show those you authored
- [x] Append the custom statuses to the posts in the post view the way core does for `draft` and `pending`
- [x] Set all talks to pending once submitted, not private
- [x] Remove the visibility section of the talks publish metabox
- [x] Remove the default talk status option

### CODE REVIEW

**Comment by tomjn** [comment]
Here's the list of statuses, and the updated publish box:

screen shot 2017-01-11 at 15 52 35
screen shot 2017-01-11 at 15 52 46

**Comment by tomjn** [comment]
screen shot 2017-01-11 at 16 38 56

**Comment by tomjn** [comment]
ab956c6 filters talks, but needs some additional work. Specifically, this filter works great right now before the schedule is announced, but after the schedule is announced a speaker will only be able to see their own talks. It's probably a simple check to add, but my brain is not seeing it right now.

This filter should also allow the talk query helper functions to be simplified. All of this is a non-issue though if the talk post type is never shown on the frontend

**Comment by tomjn** [comment]
> ah I see, if I change the filter to only show your own talks so it only applies to the frontend UI parts of the plugin, not the entire site, and then in the admin area it shows you either your talks, or all of them if you've got the access

https://wordpress.slack.com/archives/meta-wordcamp/p1484154663001045

**Comment by tomjn** [comment]
@imath the latest commits may cause bugs in some places related to visibility, I have testing to do regarding warnings/errors, but for logic problems I need another set of eyes to go through

**Comment by imath** [comment]
i guess. Well if default status is pending from now on, at least one of the feature that was allowing the user to edit the talk will be a bit more complex. Private was pretty convenient but i remember you said having a better plan during one of our chat, so it should be fine.

imath.
http://profiles.wordpress.org/imath/

**Comment by tomjn** [comment]
The filters I added should resolve the problem of visibility, but it needs a check through, especially when it comes to checks, as a lot of them relied on the private status to determine wether a UI should show or if an action could be taken

**Comment by imath** [comment]
👍

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
@tomjn I've tested the patch. And i think we'd need some wiki pages to explain how the plugin used to work, what we keep, what we improve and what we remove...

As a Speaker
=========

So here's what i've done. As a subscriber i submitted a talk, once done i got the Talks archive screen with these feedbacks:

capture d ecran 2017-01-21 a 12 36 47

Before the subscriber used to be redirected to the privately published post:

capture d ecran 2017-01-21 a 12 41 05

As we don't do previews, it was pretty convenient for the speaker to see his talk and eventually edit the talk. (There's an edit talk link just after the user's avatar under the talk content).

When the User go to his profile, he can't see the talks he submitted, and all the tabs are listed. 

capture d ecran 2017-01-21 a 12 32 22

Before as he is a speaker he could only see his profile and the talks he submitted

capture d ecran 2017-01-21 a 13 08 45

For a speaker it's great if he can edit his talk (it was restricted to one hour after submission), view his talk to be sure it has been saved etc.. And as he can submit more than one talk, viewing all the talks he submitted is also interesting.

As an admin / juror / rater
==================

These 3 roles can't view submitted talks from the front end anymore, they can't comment it, they can't rate it anymore, so they can't review it.

capture d ecran 2017-01-21 a 13 15 12

Before they were able to view all submitted talks on front end, comment them, rate them etc..

capture d ecran 2017-01-21 a 13 43 51

When i go in the dashboard, there are no talks listed in the Pending view, although the submitted talk from the front end is in database:

capture d ecran 2017-01-21 a 12 45 30

Database: 

capture d ecran 2017-01-21 a 12 49 44

As an admin i've published a talk, and then i was able to view the status selectbox. If i change this published talk to a pending status from the admin it was listed into the pending view.
So it looks like something is going wrong **when the talk is submitted from the front-end**.


On a more global point of view:
------------------------------
I agree it's an enhancement to use WordPress post status instead of the postmeta i was using, but we should make sure a "pending" talk:
- can be viewed on the front end by the author, admin, juror and raters
- cannot be viewed by other speakers or users.
- can be rated by admin/juror/raters, making sure blind raters cannot see the ratings made by others
- can be commented by admin/juror/reviewers, making sure blind raters cannot see the comments made by others, and making sure the author cannot view comments or posts comments.

The plugin is adding a front end profile feature on front end, we need to think about should we keep it? The main benefit was for raters who were able to list the talks they hadn't rated yet.

If you want to see the plugin live, you can register on http://imath-wctalks.pf1.wpserveur.net/talks/action/sign-up/ I'll promote you as an admin and you'll be able to create as many users as you wish and compare the enhancements with the existing plugin.

**Comment by jennybeaumont** [comment]
After discussing with Mathieu, we think it would be a good idea to add a final status "published". "Selected" represents the moment when organizers (or the jury) have decided to retain the talk for the program. But before publishing it to the program and the site, there is still a process of communication with the applicant in which 1) they confirm they're still willing and able to participate, 2) organizers ask for a final version of their presentation text in case there are any changes to be made.

So in all we'd be looking at 5 statuses—or phases of the submission, selection and publication process:
1) Pending
2) Shortlisted
3) Rejected
4) Selected (or accepted)
5) Published

**Comment by tomjn** [comment]
There are some issues at the moment I haven't been able to address, by removing the hardcoded `private` status checks in the frontend UI, I was unsure of the results, and was unable to test locally due to lack of time. Given the time I could go through it but since @imath is more familiar with the code I thought it best to ask for input on the locations that the checks need adjusting.

Hence the issues mentioned above, my work has been WP Admin centric, moving outwards from it, rather than towards it from the frontend. There's also the WC Talk query object and functions which obfuscate some of this that I'm keen to replace with standard `WP_Query` calls, which should make it easier to understand

**Pull request merged**
